/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var template_pb = require('./template_pb.js');
var payload_pb = require('./payload_pb.js');
goog.exportSymbol('proto.template_pb.Receipt', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.template_pb.Receipt = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.template_pb.Receipt, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.template_pb.Receipt.displayName = 'proto.template_pb.Receipt';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.template_pb.Receipt.prototype.toObject = function(opt_includeInstance) {
  return proto.template_pb.Receipt.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.template_pb.Receipt} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.template_pb.Receipt.toObject = function(includeInstance, msg) {
  var f, obj = {
    date: jspb.Message.getFieldWithDefault(msg, 1, 0),
    stateAddress: jspb.Message.getFieldWithDefault(msg, 2, ""),
    rpcMethod: jspb.Message.getFieldWithDefault(msg, 3, 0),
    template: (f = msg.getTemplate()) && template_pb.Template.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.template_pb.Receipt}
 */
proto.template_pb.Receipt.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.template_pb.Receipt;
  return proto.template_pb.Receipt.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.template_pb.Receipt} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.template_pb.Receipt}
 */
proto.template_pb.Receipt.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDate(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStateAddress(value);
      break;
    case 3:
      var value = /** @type {!proto.template_pb.Method} */ (reader.readEnum());
      msg.setRpcMethod(value);
      break;
    case 4:
      var value = new template_pb.Template;
      reader.readMessage(value,template_pb.Template.deserializeBinaryFromReader);
      msg.setTemplate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.template_pb.Receipt.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.template_pb.Receipt.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.template_pb.Receipt} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.template_pb.Receipt.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDate();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getStateAddress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRpcMethod();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getTemplate();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      template_pb.Template.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 date = 1;
 * @return {number}
 */
proto.template_pb.Receipt.prototype.getDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.template_pb.Receipt.prototype.setDate = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string state_address = 2;
 * @return {string}
 */
proto.template_pb.Receipt.prototype.getStateAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.template_pb.Receipt.prototype.setStateAddress = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Method rpc_method = 3;
 * @return {!proto.template_pb.Method}
 */
proto.template_pb.Receipt.prototype.getRpcMethod = function() {
  return /** @type {!proto.template_pb.Method} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.template_pb.Method} value */
proto.template_pb.Receipt.prototype.setRpcMethod = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional Template template = 4;
 * @return {?proto.template_pb.Template}
 */
proto.template_pb.Receipt.prototype.getTemplate = function() {
  return /** @type{?proto.template_pb.Template} */ (
    jspb.Message.getWrapperField(this, template_pb.Template, 4));
};


/** @param {?proto.template_pb.Template|undefined} value */
proto.template_pb.Receipt.prototype.setTemplate = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.template_pb.Receipt.prototype.clearTemplate = function() {
  this.setTemplate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.template_pb.Receipt.prototype.hasTemplate = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.template_pb);
