// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payload.proto

package template_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Method int32

const (
	Method_CREATE Method = 0
	Method_UPDATE Method = 1
	Method_DELETE Method = 2
)

var Method_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
}
var Method_value = map[string]int32{
	"CREATE": 0,
	"UPDATE": 1,
	"DELETE": 2,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}
func (Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_payload_18ae87993a33de77, []int{0}
}

type RPCRequest struct {
	Method               Method    `protobuf:"varint,1,opt,name=method,proto3,enum=template_pb.Method" json:"method,omitempty"`
	Params               *Template `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RPCRequest) Reset()         { *m = RPCRequest{} }
func (m *RPCRequest) String() string { return proto.CompactTextString(m) }
func (*RPCRequest) ProtoMessage()    {}
func (*RPCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_payload_18ae87993a33de77, []int{0}
}
func (m *RPCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCRequest.Unmarshal(m, b)
}
func (m *RPCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCRequest.Marshal(b, m, deterministic)
}
func (dst *RPCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCRequest.Merge(dst, src)
}
func (m *RPCRequest) XXX_Size() int {
	return xxx_messageInfo_RPCRequest.Size(m)
}
func (m *RPCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RPCRequest proto.InternalMessageInfo

func (m *RPCRequest) GetMethod() Method {
	if m != nil {
		return m.Method
	}
	return Method_CREATE
}

func (m *RPCRequest) GetParams() *Template {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*RPCRequest)(nil), "template_pb.RPCRequest")
	proto.RegisterEnum("template_pb.Method", Method_name, Method_value)
}

func init() { proto.RegisterFile("payload.proto", fileDescriptor_payload_18ae87993a33de77) }

var fileDescriptor_payload_18ae87993a33de77 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0xac, 0xcc,
	0xc9, 0x4f, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2e, 0x49, 0xcd, 0x2d, 0xc8,
	0x49, 0x2c, 0x49, 0x8d, 0x2f, 0x48, 0x92, 0xe2, 0x83, 0x71, 0x20, 0x92, 0x4a, 0x19, 0x5c, 0x5c,
	0x41, 0x01, 0xce, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xda, 0x5c, 0x6c, 0xb9, 0xa9,
	0x25, 0x19, 0xf9, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0xc2, 0x7a, 0x48, 0x7a, 0xf5,
	0x7c, 0xc1, 0x52, 0x41, 0x50, 0x25, 0x42, 0xba, 0x5c, 0x6c, 0x05, 0x89, 0x45, 0x89, 0xb9, 0xc5,
	0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xa2, 0x28, 0x8a, 0x43, 0xa0, 0xec, 0x20, 0xa8, 0x22,
	0x2d, 0x1d, 0x2e, 0x36, 0x88, 0x01, 0x42, 0x5c, 0x5c, 0x6c, 0xce, 0x41, 0xae, 0x8e, 0x21, 0xae,
	0x02, 0x0c, 0x20, 0x76, 0x68, 0x80, 0x0b, 0x88, 0xcd, 0x08, 0x62, 0xbb, 0xb8, 0xfa, 0xb8, 0x86,
	0xb8, 0x0a, 0x30, 0x39, 0xf1, 0x46, 0x21, 0x3b, 0x3b, 0x89, 0x0d, 0xec, 0x5a, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x8e, 0x83, 0x2a, 0x80, 0xdb, 0x00, 0x00, 0x00,
}
