// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payload.proto

package badgeforce_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Method int32

const (
	Method_CREATE Method = 0
	Method_UPDATE Method = 1
	Method_DELETE Method = 2
)

var Method_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
}
var Method_value = map[string]int32{
	"CREATE": 0,
	"UPDATE": 1,
	"DELETE": 2,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}
func (Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_payload_f30194b0237e99ff, []int{0}
}

type RPCRequest struct {
	// Types that are valid to be assigned to Method:
	//	*RPCRequest_Create
	//	*RPCRequest_Delete
	Method               isRPCRequest_Method `protobuf_oneof:"method"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RPCRequest) Reset()         { *m = RPCRequest{} }
func (m *RPCRequest) String() string { return proto.CompactTextString(m) }
func (*RPCRequest) ProtoMessage()    {}
func (*RPCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_payload_f30194b0237e99ff, []int{0}
}
func (m *RPCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCRequest.Unmarshal(m, b)
}
func (m *RPCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCRequest.Marshal(b, m, deterministic)
}
func (dst *RPCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCRequest.Merge(dst, src)
}
func (m *RPCRequest) XXX_Size() int {
	return xxx_messageInfo_RPCRequest.Size(m)
}
func (m *RPCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RPCRequest proto.InternalMessageInfo

type isRPCRequest_Method interface {
	isRPCRequest_Method()
}

type RPCRequest_Create struct {
	Create *Create `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type RPCRequest_Delete struct {
	Delete *Delete `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

func (*RPCRequest_Create) isRPCRequest_Method() {}

func (*RPCRequest_Delete) isRPCRequest_Method() {}

func (m *RPCRequest) GetMethod() isRPCRequest_Method {
	if m != nil {
		return m.Method
	}
	return nil
}

func (m *RPCRequest) GetCreate() *Create {
	if x, ok := m.GetMethod().(*RPCRequest_Create); ok {
		return x.Create
	}
	return nil
}

func (m *RPCRequest) GetDelete() *Delete {
	if x, ok := m.GetMethod().(*RPCRequest_Delete); ok {
		return x.Delete
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*RPCRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _RPCRequest_OneofMarshaler, _RPCRequest_OneofUnmarshaler, _RPCRequest_OneofSizer, []interface{}{
		(*RPCRequest_Create)(nil),
		(*RPCRequest_Delete)(nil),
	}
}

func _RPCRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*RPCRequest)
	// method
	switch x := m.Method.(type) {
	case *RPCRequest_Create:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Create); err != nil {
			return err
		}
	case *RPCRequest_Delete:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Delete); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("RPCRequest.Method has unexpected type %T", x)
	}
	return nil
}

func _RPCRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*RPCRequest)
	switch tag {
	case 1: // method.create
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Create)
		err := b.DecodeMessage(msg)
		m.Method = &RPCRequest_Create{msg}
		return true, err
	case 2: // method.delete
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Delete)
		err := b.DecodeMessage(msg)
		m.Method = &RPCRequest_Delete{msg}
		return true, err
	default:
		return false, nil
	}
}

func _RPCRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*RPCRequest)
	// method
	switch x := m.Method.(type) {
	case *RPCRequest_Create:
		s := proto.Size(x.Create)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *RPCRequest_Delete:
		s := proto.Size(x.Delete)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Create struct {
	Params               *Template `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Create) Reset()         { *m = Create{} }
func (m *Create) String() string { return proto.CompactTextString(m) }
func (*Create) ProtoMessage()    {}
func (*Create) Descriptor() ([]byte, []int) {
	return fileDescriptor_payload_f30194b0237e99ff, []int{1}
}
func (m *Create) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Create.Unmarshal(m, b)
}
func (m *Create) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Create.Marshal(b, m, deterministic)
}
func (dst *Create) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Create.Merge(dst, src)
}
func (m *Create) XXX_Size() int {
	return xxx_messageInfo_Create.Size(m)
}
func (m *Create) XXX_DiscardUnknown() {
	xxx_messageInfo_Create.DiscardUnknown(m)
}

var xxx_messageInfo_Create proto.InternalMessageInfo

func (m *Create) GetParams() *Template {
	if m != nil {
		return m.Params
	}
	return nil
}

type Delete struct {
	Addresses            []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delete) Reset()         { *m = Delete{} }
func (m *Delete) String() string { return proto.CompactTextString(m) }
func (*Delete) ProtoMessage()    {}
func (*Delete) Descriptor() ([]byte, []int) {
	return fileDescriptor_payload_f30194b0237e99ff, []int{2}
}
func (m *Delete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delete.Unmarshal(m, b)
}
func (m *Delete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delete.Marshal(b, m, deterministic)
}
func (dst *Delete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delete.Merge(dst, src)
}
func (m *Delete) XXX_Size() int {
	return xxx_messageInfo_Delete.Size(m)
}
func (m *Delete) XXX_DiscardUnknown() {
	xxx_messageInfo_Delete.DiscardUnknown(m)
}

var xxx_messageInfo_Delete proto.InternalMessageInfo

func (m *Delete) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func init() {
	proto.RegisterType((*RPCRequest)(nil), "badgeforce_pb.RPCRequest")
	proto.RegisterType((*Create)(nil), "badgeforce_pb.Create")
	proto.RegisterType((*Delete)(nil), "badgeforce_pb.Delete")
	proto.RegisterEnum("badgeforce_pb.Method", Method_name, Method_value)
}

func init() { proto.RegisterFile("payload.proto", fileDescriptor_payload_f30194b0237e99ff) }

var fileDescriptor_payload_f30194b0237e99ff = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x14, 0x84, 0xbb, 0x15, 0x82, 0x7d, 0x52, 0x2d, 0x01, 0xb1, 0x88, 0x07, 0xd9, 0x83, 0x14, 0x91,
	0x15, 0xf4, 0xe4, 0xd1, 0x66, 0x03, 0x1e, 0x14, 0x4a, 0x58, 0x2f, 0x5e, 0xe4, 0x6d, 0xf3, 0xd4,
	0xc3, 0x2e, 0x89, 0x49, 0x04, 0xfd, 0xf7, 0x92, 0x6c, 0x50, 0x56, 0xbc, 0x0d, 0x99, 0xf9, 0xe6,
	0x85, 0x81, 0xb9, 0xc5, 0xaf, 0xce, 0xa0, 0xae, 0xac, 0x33, 0xc1, 0xf0, 0x79, 0x8b, 0xfa, 0x95,
	0x5e, 0x8c, 0xdb, 0xd2, 0xb3, 0x6d, 0x8f, 0xf7, 0x03, 0xf5, 0xb6, 0xc3, 0x40, 0x83, 0x5d, 0x7e,
	0x02, 0xa8, 0x8d, 0x50, 0xf4, 0xfe, 0x41, 0x3e, 0xf0, 0x4b, 0x60, 0x5b, 0x47, 0x18, 0x68, 0x59,
	0x9c, 0x16, 0xab, 0xbd, 0xab, 0xc3, 0x6a, 0x44, 0x57, 0x22, 0x99, 0x77, 0x13, 0x95, 0x63, 0x11,
	0xd0, 0xd4, 0x51, 0xa0, 0xe5, 0xf4, 0x5f, 0xa0, 0x4e, 0x66, 0x04, 0x86, 0xd8, 0x7a, 0x17, 0x58,
	0x4f, 0xe1, 0xcd, 0xe8, 0xf2, 0x06, 0x98, 0xf8, 0x29, 0xb1, 0xe8, 0xb0, 0xf7, 0xf9, 0xea, 0xd1,
	0x9f, 0x92, 0x26, 0x7f, 0x59, 0xe5, 0x58, 0x79, 0x06, 0x6c, 0x28, 0xe6, 0x27, 0x30, 0x43, 0xad,
	0x1d, 0x79, 0x4f, 0x91, 0xde, 0x59, 0xcd, 0xd4, 0xef, 0xc3, 0xf9, 0x05, 0xb0, 0x87, 0x74, 0x8c,
	0x03, 0x30, 0xa1, 0xe4, 0x6d, 0x23, 0x17, 0x93, 0xa8, 0x1f, 0x37, 0x75, 0xd4, 0x45, 0xd4, 0xb5,
	0xbc, 0x97, 0x8d, 0x5c, 0x4c, 0xd7, 0x07, 0x4f, 0xe3, 0xad, 0x5a, 0x96, 0x26, 0xba, 0xfe, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0xa0, 0xa4, 0x22, 0xb5, 0x52, 0x01, 0x00, 0x00,
}
